project_id = "aiihzjkspwsriktvrdle"

[functions.generate-learning-roadmap]
verify_jwt = true

[functions.generate-team-insights]
verify_jwt = true

[functions.create-employee]
verify_jwt = true

[functions.reset-employee-password]
verify_jwt = true

[functions.analyze-job-description]
verify_jwt = true

[functions.recommend-resources]
verify_jwt = true

[functions.chat-with-jericho]
verify_jwt = false

[functions.help-write-goal]
verify_jwt = true

[functions.suggest-habits]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.extract-review-content]
verify_jwt = true

[functions.generate-performance-review]
verify_jwt = true

[functions.notify-capability-change]
verify_jwt = true
