-- Update full descriptions for missing capabilities
UPDATE capabilities SET full_description = 'The ability to create clear, comprehensive documentation that enables others to understand systems, processes, and technical work effectively.' WHERE name = 'Documentation';
UPDATE capabilities SET full_description = 'Deep knowledge and expertise in a specific business domain, industry, or functional area that enables strategic contributions and specialized problem-solving.' WHERE name = 'Domain Expertise';
UPDATE capabilities SET full_description = 'The ability to establish and maintain quality standards, identify defects and issues, and ensure deliverables meet requirements and expectations.' WHERE name = 'Quality Assurance';
UPDATE capabilities SET full_description = 'Proficiency in using the tools, software, and technologies required to perform job responsibilities effectively and efficiently.' WHERE name = 'Tool Proficiency';

-- Documentation levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Creates basic documentation for simple processes or tasks. May struggle with organization or completeness. Documentation may be unclear to others without explanation. Learning what level of detail is needed. May avoid documentation unless required. Updates documentation inconsistently. Benefits from templates and examples.' FROM capabilities WHERE name = 'Documentation' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Creates clear, organized documentation for standard processes and work. Writes documentation that others can follow without assistance. Includes appropriate level of detail for the audience. Updates documentation regularly to keep it current. Uses consistent formatting and structure. Recognizes when documentation would add value.' FROM capabilities WHERE name = 'Documentation' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Creates comprehensive documentation for complex systems and processes. Writes documentation that serves multiple audiences effectively. Anticipates what information users will need. Creates documentation standards for team use. Makes complex information accessible and easy to understand. Known for excellent documentation that saves time and reduces questions.' FROM capabilities WHERE name = 'Documentation' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Sets organizational standards for documentation excellence. Designs documentation systems and frameworks used enterprise-wide. Creates documentation that becomes the definitive reference. Coaches others on creating effective documentation. Influences how the organization values and maintains documentation. Sought out to document the most complex and critical systems. Known for documentation that enables organizational knowledge transfer and continuity.' FROM capabilities WHERE name = 'Documentation' ON CONFLICT DO NOTHING;

-- Domain Expertise levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Learning the fundamentals of the domain or industry. Understands basic terminology and concepts. Asks questions to build domain knowledge. Relies on others for domain-specific guidance. Beginning to see how domain knowledge applies to work. May not yet recognize domain-specific nuances or complexities.' FROM capabilities WHERE name = 'Domain Expertise' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Demonstrates solid understanding of the domain. Applies domain knowledge to day-to-day work independently. Stays current with domain developments and trends. Understands domain-specific regulations, standards, or best practices. Can explain domain concepts to others. Contributes domain insights to team discussions.' FROM capabilities WHERE name = 'Domain Expertise' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Expert-level domain knowledge that others rely on. Applies deep domain expertise to solve complex problems. Anticipates domain trends and their implications. Connects domain knowledge to business strategy. Recognized internally as a domain authority. Stays at the forefront of domain developments. Mentors others in building domain expertise.' FROM capabilities WHERE name = 'Domain Expertise' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Thought leader who shapes domain standards and practices. Recognized externally as a domain authority (speaks at conferences, publishes, etc.). Advises senior leadership on domain-related strategy. Builds domain expertise capability across the organization. Influences industry direction through domain leadership. Sought out by executives for domain expertise on critical decisions. Sets the standard for domain excellence in the organization.' FROM capabilities WHERE name = 'Domain Expertise' ON CONFLICT DO NOTHING;

-- Quality Assurance levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Understands the importance of quality standards. Follows quality checklists and procedures when provided. Identifies obvious quality issues or defects. May miss subtle quality problems. Learning what constitutes quality in their work. Relies on others to catch quality issues before delivery. Improves quality with feedback and practice.' FROM capabilities WHERE name = 'Quality Assurance' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Consistently delivers quality work that meets standards. Reviews own work systematically before delivery. Identifies most quality issues before they reach others. Understands trade-offs between quality and speed. Suggests quality improvements to processes. Uses quality tools and techniques effectively. Known for delivering reliable, quality work.' FROM capabilities WHERE name = 'Quality Assurance' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Establishes quality standards and processes for team or projects. Identifies systemic quality issues and root causes. Implements quality controls that prevent defects. Balances quality with practical constraints skillfully. Catches critical quality issues others miss. Coaches others on quality practices. Serves as quality reviewer for high-stakes deliverables. Known for exceptional quality standards.' FROM capabilities WHERE name = 'Quality Assurance' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Designs quality assurance systems used organization-wide. Shapes organizational culture around quality and excellence. Influences industry quality standards and practices. Sought out for quality leadership on the most critical initiatives. Builds quality capability across the organization. Balances quality excellence with innovation and speed. Prevents costly quality failures through systematic approaches. Sets the benchmark for quality as a competitive advantage.' FROM capabilities WHERE name = 'Quality Assurance' ON CONFLICT DO NOTHING;

-- Tool Proficiency levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Uses basic features of core tools with guidance. Learning which tools to use for different tasks. May struggle with efficiency or best practices. Asks for help when stuck with tools. Comfortable with routine tasks but challenged by advanced features. Building foundational skills through practice and training.' FROM capabilities WHERE name = 'Tool Proficiency' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Uses core tools proficiently for day-to-day work. Knows which tool to use for different situations. Leverages tool features to work efficiently. Troubleshoots common tool issues independently. Learns new tools relatively quickly. Helps less experienced colleagues with tool questions. Stays current with tool updates and new features.' FROM capabilities WHERE name = 'Tool Proficiency' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Expert-level proficiency with core tools and technologies. Maximizes tool capabilities to optimize work and solve problems. Quickly masters new tools as needed. Creates tool templates, shortcuts, or workflows that others use. Integrates multiple tools effectively. Evaluates and recommends new tools. Known as the go-to person for tool expertise. Trains others on tool best practices.' FROM capabilities WHERE name = 'Tool Proficiency' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Shapes organizational tool strategy and standards. Evaluates and implements enterprise tool solutions. Builds tool proficiency capability across the organization. Creates tool ecosystems that maximize productivity. Influences vendor tool development through strategic partnerships. Sought out by leadership for tool strategy decisions. Known for transforming how the organization leverages technology tools. Sets the standard for tool excellence and innovation.' FROM capabilities WHERE name = 'Tool Proficiency' ON CONFLICT DO NOTHING;