-- Accountability levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Takes responsibility for assigned tasks. Follows through on commitments with reminders. Acknowledges mistakes when pointed out. May make excuses or blame external factors when things go wrong. Learning to proactively track and report on commitments. Meets most deadlines with support and follow-up.' FROM capabilities WHERE name = 'Accountability' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Consistently delivers on commitments without reminders. Proactively communicates if deadlines or deliverables are at risk. Tracks own commitments and follows through independently. Delivers quality work on time consistently. Holds others accountable in peer situations. Known as reliable and dependable.' FROM capabilities WHERE name = 'Accountability' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Takes full ownership of outcomes, not just activities. Holds self accountable to the highest standards. Addresses problems proactively rather than waiting for others to notice. Delivers results even in challenging circumstances. Creates culture of accountability on teams. Known for being someone you can count on completely. Takes accountability without making excuses.' FROM capabilities WHERE name = 'Accountability' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Drives accountability as an organizational capability. Holds the most senior leaders accountable respectfully and effectively. Sought out to lead initiatives where accountability has been lacking. Known for creating cultures where everyone owns their commitments and outcomes.' FROM capabilities WHERE name = 'Accountability' ON CONFLICT DO NOTHING;

-- Time Management levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Completes assigned tasks within reasonable timeframes. May struggle with prioritization or competing demands. Sometimes misses deadlines or needs extensions. Learning to estimate how long tasks will take. May get distracted or sidetracked easily. Uses basic tools (calendar, to-do lists) inconsistently. Relies on manager to help prioritize workload.' FROM capabilities WHERE name = 'Time Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Manages time effectively for routine workload. Prioritizes tasks based on importance and urgency. Meets deadlines consistently. Estimates time requirements accurately for most tasks. Uses time management tools and techniques effectively. Minimizes time-wasters and distractions. Communicates proactively when workload becomes unmanageable.' FROM capabilities WHERE name = 'Time Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Optimizes time to maximize productivity and impact. Prioritizes ruthlessly based on strategic value. Manages complex, competing priorities across multiple projects. Protects time for high-value activities. Delegates or declines low-value work appropriately. Maintains effectiveness even with heavy workload. Helps others improve their time management.' FROM capabilities WHERE name = 'Time Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Masters time as a strategic resource. Creates systems and norms that improve organizational productivity. Models time management that cascades through teams. Protects organizational focus on highest-value activities. Coaches leaders on strategic time management. Eliminates time-wasting practices at scale. Sought out for counsel on prioritization of major initiatives. Known for achieving extraordinary results through disciplined time management. Sets the standard for productivity and focus.' FROM capabilities WHERE name = 'Time Management' ON CONFLICT DO NOTHING;

-- Attention to Detail levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Completes work with basic accuracy. May overlook errors or details that need attention. Benefits from review and quality checks by others. Learning where precision matters most. May rush through work and miss important details. Improves accuracy with feedback and practice.' FROM capabilities WHERE name = 'Attention to Detail' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Produces accurate, thorough work consistently. Catches most errors before submission. Knows when precision matters vs. when "good enough" is sufficient. Reviews own work systematically. Rarely requires corrections or revisions. Maintains quality even under time pressure. Known for delivering clean, polished work.' FROM capabilities WHERE name = 'Attention to Detail' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Produces flawless work even on complex deliverables. Spots errors and issues others miss. Ensures detail excellence without getting lost in minutiae. Creates quality control processes for self and team. Serves as final reviewer for high-stakes work. Raises quality standards for the team. Known for exceptional accuracy and thoroughness. Catches errors that would have significant consequences.' FROM capabilities WHERE name = 'Attention to Detail' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Sets organizational standards for quality and precision. Designs quality assurance systems used across the organization. Ensures detail excellence on the most critical work. Balances precision with innovation and risk-taking appropriately. Builds culture where quality is everyone''s responsibility. Coaches others on attention to detail without perfectionism. Prevents costly errors through systematic approaches. Sought out to review the most important deliverables. Known for setting the bar for excellence. Balances attention to detail with strategic thinking.' FROM capabilities WHERE name = 'Attention to Detail' ON CONFLICT DO NOTHING;

-- Planning & Organization levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Creates basic plans for simple projects and tasks. May struggle with complex planning or longer timeframes. Keeps basic organizational systems (files, calendar, notes). Needs guidance to break down large projects into steps. May lose track of details or commitments. Learning planning frameworks and tools.' FROM capabilities WHERE name = 'Planning & Organization' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Plans and organizes work effectively for routine projects. Breaks down complex work into manageable steps. Maintains organized systems for tracking work and information. Anticipates resource needs and potential obstacles. Uses planning tools proficiently. Keeps stakeholders informed of plans and progress. Adjusts plans when circumstances change.' FROM capabilities WHERE name = 'Planning & Organization' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Develops comprehensive plans for complex initiatives. Creates systems that keep multiple projects organized simultaneously. Anticipates dependencies and potential obstacles proactively. Plans strategically while remaining flexible. Balances detailed planning with ability to adapt. Coaches others on planning and organization. Known for turning complex challenges into executable plans.' FROM capabilities WHERE name = 'Planning & Organization' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Drives organizational planning at the enterprise level. Designs planning frameworks and systems used across the organization. Orchestrates complex, multi-year strategic plans. Creates organizational structures and processes that enable execution. Builds planning capability across leadership teams. Balances strategic planning with organizational agility. Sought out to plan the most complex enterprise initiatives. Influences how the organization balances detailed planning with flexibility and execution. Known for turning ambitious visions into executable plans. Sets the standard for strategic planning and organization.' FROM capabilities WHERE name = 'Planning & Organization' ON CONFLICT DO NOTHING;

-- Results Orientation levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Focuses on completing assigned tasks. Understands the importance of achieving goals. May prioritize activity over outcomes. Needs guidance to define what success looks like. Celebrates effort more than results. Learning to measure success by impact rather than just completion. Building drive to achieve targets.' FROM capabilities WHERE name = 'Results Orientation' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Consistently achieves goals and targets. Focuses energy on activities that drive results. Takes initiative to exceed expectations. Measures success by outcomes, not just effort. Persists through obstacles to achieve goals. Balances quality with speed to deliver results. Holds self accountable for results. Known for getting things done.' FROM capabilities WHERE name = 'Results Orientation' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Drives exceptional results consistently. Sets ambitious goals and achieves them. Removes obstacles and finds creative paths to success. Focuses team energy on highest-impact activities. Delivers results even in challenging circumstances. Balances results with values, people development, and sustainability. Builds results orientation across teams.' FROM capabilities WHERE name = 'Results Orientation' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Creates culture of results and high performance. Delivers on the organization''s most critical objectives. Influences how the organization defines and measures success. Sought out to lead the most important strategic initiatives. Known for delivering what others consider impossible. Sets the standard for achievement and impact.' FROM capabilities WHERE name = 'Results Orientation' ON CONFLICT DO NOTHING;

-- Change Management levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Understands that change is happening. Follows new processes and procedures when instructed. May be uncertain or anxious about changes. Asks questions to understand changes. Adapts personal work when change is explained clearly. Participates in change initiatives when asked.' FROM capabilities WHERE name = 'Change Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Helps others understand and adapt to changes. Communicates change rationale to team members. Identifies potential resistance and addresses concerns. Supports change initiatives actively. Models positive response to organizational changes. Helps team navigate transitions smoothly.' FROM capabilities WHERE name = 'Change Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Leads change initiatives effectively. Develops change management plans with stakeholder analysis and communication strategies. Builds buy-in across diverse groups. Anticipates and mitigates resistance proactively. Balances urgency with people''s ability to adapt. Measures and adjusts change approach based on feedback. Known for successfully implementing significant changes.' FROM capabilities WHERE name = 'Change Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Leads transformational organizational change. Designs change strategies for enterprise-wide initiatives. Builds change capability across the organization. Influences organizational culture to embrace continuous change. Coaches senior leaders through major transitions. Sought out for the most complex organizational transformations. Known for successfully leading change that others thought impossible. Sets the standard for change leadership.' FROM capabilities WHERE name = 'Change Management' ON CONFLICT DO NOTHING;