-- Collaboration levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Works cooperatively with immediate team members. Participates in team meetings and group projects. Shares information when asked. May default to working independently rather than seeking collaboration. Building trust with colleagues. May struggle with group dynamics or differing work styles. Open to feedback and others'' ideas.' FROM capabilities WHERE name = 'Collaboration' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Actively collaborates across the team and with other departments. Seeks input from others proactively. Shares information, resources, and credit willingly. Adapts to different collaboration styles and preferences. Contributes meaningfully to team discussions and decisions. Resolves minor collaboration hiccups directly.' FROM capabilities WHERE name = 'Collaboration' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Drives collaboration across teams, functions, and organizational boundaries. Builds strong collaborative relationships at all levels. Creates environments where collaboration thrives. Navigates complex group dynamics skillfully. Bridges silos and brings diverse groups together. Facilitates productive collaboration on challenging initiatives.' FROM capabilities WHERE name = 'Collaboration' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Transforms how the organization collaborates. Builds collaborative cultures and ecosystems. Forges strategic partnerships within and outside the organization. Resolves collaboration breakdowns at the highest levels. Creates structures and processes that enable collaboration at scale. Coaches senior leaders on building collaborative teams. Influences organizational values and norms around teamwork. Sought out to lead the most complex cross-functional initiatives. Sets the standard for collaboration as competitive advantage.' FROM capabilities WHERE name = 'Collaboration' ON CONFLICT DO NOTHING;

-- Relationship Building levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Builds basic working relationships with immediate colleagues. Friendly and approachable in professional settings. Participates in team social activities. May be reserved or take time to warm up to new people. Learning to build rapport beyond surface-level interactions. Maintains existing relationships but may not proactively expand network. Shows genuine interest in getting to know colleagues.' FROM capabilities WHERE name = 'Relationship Building' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Builds positive relationships across the team and organization. Makes effort to connect with new people and expand network. Maintains relationships over time through regular contact. Finds common ground with diverse personalities. Balances professional relationships with appropriate personal connection. Leverages relationships to get work done more effectively. Known as someone people enjoy working with.' FROM capabilities WHERE name = 'Relationship Building' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Builds strong, trust-based relationships at all levels. Networks strategically within and outside the organization. Cultivates relationships before they''re needed for a specific purpose. Maintains a broad network across functions, levels, and geographies. Turns professional relationships into genuine partnerships. Leverages relationships to create opportunities and solve problems. Known as a connector who brings people together.' FROM capabilities WHERE name = 'Relationship Building' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Master relationship builder with extensive, influential network. Builds strategic partnerships that create value for the organization. Cultivates relationships with key external stakeholders (clients, partners, industry leaders). Opens doors and creates opportunities others can''t access. Maintains relationships across their entire career. Builds relationship-building capability in others. Creates organizational culture where relationships are valued. Sought out to build bridges to important external partners.' FROM capabilities WHERE name = 'Relationship Building' ON CONFLICT DO NOTHING;

-- Emotional Intelligence levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Recognizes basic emotions in self and others. Shows empathy in straightforward situations. May struggle to manage emotions under stress. Learning to read emotional cues and respond appropriately. Accepts feedback about emotional responses. Beginning to understand impact of emotions on work and relationships. May be unaware of how their emotions affect others.' FROM capabilities WHERE name = 'Emotional Intelligence' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Aware of own emotions and can usually manage them effectively. Reads others'' emotions and responds with empathy. Stays composed under normal stress. Considers emotional dynamics in interactions. Adjusts approach based on others'' emotional states. Builds trust through emotional awareness. Handles most interpersonal situations skillfully.' FROM capabilities WHERE name = 'Emotional Intelligence' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Highly attuned to emotional dynamics in individuals and groups. Manages own emotions effectively even in difficult situations. Helps others navigate their emotions constructively. Uses emotional intelligence to build strong relationships and resolve conflicts. Remains composed and effective in high-stress situations. Shows deep empathy while maintaining appropriate boundaries. Creates psychologically safe environments for others. Helps others manage their emotions constructively.' FROM capabilities WHERE name = 'Emotional Intelligence' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Master of emotional intelligence who transforms relationships and culture. Coaches senior leaders on emotional intelligence development. Creates organizational cultures of psychological safety and trust. Uses emotional intelligence strategically to drive outcomes. Handles emotionally charged situations (crisis, trauma, conflict) with exceptional skill. Influences how the organization thinks about emotions at work. Sought out for situations requiring emotional sophistication. Sets the standard for emotional intelligence as a leadership capability and bringing out the best in people emotionally.' FROM capabilities WHERE name = 'Emotional Intelligence' ON CONFLICT DO NOTHING;

-- Adaptability levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Adjusts to minor changes with guidance and support. May resist or feel uncomfortable with significant change. Needs time to process and adapt to new situations. Prefers familiar routines and processes. Learning to see change as opportunity rather than threat. Asks questions to understand why changes are happening. Can adapt when change is clearly explained and supported.' FROM capabilities WHERE name = 'Adaptability' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Adapts to routine changes and shifting priorities smoothly. Handles unexpected situations with composure. Adjusts approach when initial plan isn''t working. Stays productive during times of change. Helps others adjust to change. Sees change as normal part of work. Balances flexibility with maintaining quality standards. Recovers quickly from setbacks.' FROM capabilities WHERE name = 'Adaptability' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Thrives in ambiguous, rapidly changing environments. Models adaptability that others emulate. Known for staying calm and effective when everything is shifting. Balances adaptability with strategic consistency.' FROM capabilities WHERE name = 'Adaptability' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Master of navigating and leading through transformational change. Drives organizational agility and adaptability. Leads successfully through crisis, disruption, and uncertainty. Helps the organization reimagine itself in response to change. Builds adaptive cultures and systems. Sought out when the organization faces its biggest changes. Known for turning disruption into competitive advantage. Sets the standard for adaptability as organizational capability.' FROM capabilities WHERE name = 'Adaptability' ON CONFLICT DO NOTHING;

-- Influence levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Shares ideas and opinions when asked. May struggle to gain buy-in for proposals. Relies primarily on formal authority or position (if applicable). Building credibility with peers and stakeholders. Learning different influence strategies. May give up if initial attempt to influence doesn''t work. Influences primarily through facts and logic.' FROM capabilities WHERE name = 'Influence' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Influences peers and some stakeholders effectively. Builds credibility through expertise and relationships. Uses multiple influence tactics (data, emotion, coalition-building). Gains buy-in for ideas and proposals regularly. Adapts influence approach to the audience. Persists when facing resistance. Influences both up and across the organization.' FROM capabilities WHERE name = 'Influence' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Influences decisions and outcomes at senior levels. Gains support for ideas even without formal authority. Uses influence strategically to advance important initiatives. Builds coalitions around ideas. Influences through multiple channels (data, relationships, storytelling). Known for ability to gain buy-in from diverse stakeholders.' FROM capabilities WHERE name = 'Influence' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Master influencer who shapes organizational direction and culture. Influences the most senior leaders and critical decisions. Builds movements around ideas that transform the organization. Influences external stakeholders (board, investors, partners, industry). Uses influence ethically and strategically. Develops influencing capability across the organization. Shapes norms and values through consistent influence. Sought out to build support for the most important initiatives. Known as a change agent whose influence extends far beyond role. Sets the standard for principled, strategic influence.' FROM capabilities WHERE name = 'Influence' ON CONFLICT DO NOTHING;