-- Data Analysis levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Understands basic data concepts (averages, percentages, trends). Performs basic analysis with guidance (sorting, filtering, simple calculations). Uses basic Excel or spreadsheet functions. Asks clarifying questions about data sources and meaning. May struggle with data quality issues or knowing which analysis to perform. Beginning to draw insights from simple data sets.' FROM capabilities WHERE name = 'Data Analysis' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Analyzes routine data independently using appropriate tools. Creates clear visualizations (charts, graphs, dashboards) for common metrics. Identifies trends, patterns, and anomalies in data. Validates data quality and flags issues. Presents findings clearly to non-technical audiences. Uses data to support recommendations.' FROM capabilities WHERE name = 'Data Analysis' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Conducts complex analysis to solve business problems independently. Makes recommendations based on rigorous analysis. Anticipates questions and provides thorough analysis. Identifies insights that others miss. Tells compelling stories with data.' FROM capabilities WHERE name = 'Data Analysis' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Expert analyst who drives strategic decisions through data. Influences organizational data strategy and infrastructure. Sought out by executives for critical analytical work. Known for uncovering game-changing insights. Creates culture of data-driven decision making. Sets the standard for analytical excellence.' FROM capabilities WHERE name = 'Data Analysis' ON CONFLICT DO NOTHING;

-- Technical Expertise levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Learning core technical skills and concepts in their domain. Performs basic technical work with guidance and support. Asks questions to understand technical approaches. Building foundational technical knowledge. May need frequent assistance with technical challenges.' FROM capabilities WHERE name = 'Technical Expertise' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Demonstrates solid technical competence in core areas. Performs most technical work independently. Troubleshoots routine technical issues without help. Understands the "why" behind technical approaches. Stays current with relevant technical developments. Contributes technical ideas and solutions. Helps less experienced team members.' FROM capabilities WHERE name = 'Technical Expertise' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Expert-level proficiency in their technical direction. Handles complex technical challenges independently. Designs technical solutions that meet both current and future needs. Optimizes technical processes and approaches. Builds technical capability across the organization. Balances technical quality with practical constraints. Mentors others in technical skills. Recognized as a technical authority by peers.' FROM capabilities WHERE name = 'Technical Expertise' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Master technician who shapes technical standards and best practices. Represents organization as a technical thought leader externally. Sought out by senior leadership for technical counsel. Known as the technical expert others aspire to become. Bridges deep technical expertise with business strategy.' FROM capabilities WHERE name = 'Technical Expertise' ON CONFLICT DO NOTHING;

-- Project Management levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Manages simple, short-term tasks and projects with clear scope. Creates basic project plans with guidance (tasks, timelines, owners). Tracks progress and updates status. May struggle with dependencies, risks, or changes. Asks for help when projects get off track. Uses basic project management tools. Learning project management fundamentals. Focuses on task completion rather than strategic outcomes.' FROM capabilities WHERE name = 'Project Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Manages moderately complex projects independently. Creates comprehensive project plans (scope, timeline, resources, milestones). Identifies and manages risks and dependencies. Keeps stakeholders informed with regular updates. Adjusts plans when circumstances change. Balances scope, time, and resources effectively. Uses project management tools proficiently. Delivers projects on time and within scope consistently. Conducts post-project reviews to identify lessons learned.' FROM capabilities WHERE name = 'Project Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Manages complex, high-stakes projects with multiple stakeholders. Excels at scoping, planning, and executing large initiatives. Anticipates and mitigates risks proactively. Manages competing priorities and resource constraints skillfully. Influences stakeholders and navigates organizational dynamics. Adapts methodology to fit the project (agile, waterfall, hybrid). Recovers troubled projects effectively. Coaches others on project management. Known for consistently delivering complex projects successfully. Sets the standard for project management excellence.' FROM capabilities WHERE name = 'Project Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Master project manager who leads transformational initiatives. Manages portfolios of interconnected projects. Designs project management frameworks used organization-wide. Leads the most strategic, complex, and high-risk projects. Builds project management capability across the organization. Influences organizational project governance and methodology. Turns around failing programs and initiatives. Sought out by executives for critical enterprise initiatives. Known for making the impossible happen.' FROM capabilities WHERE name = 'Project Management' ON CONFLICT DO NOTHING;

-- Process Improvement levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Follows existing processes and procedures. Notices when processes are inefficient or broken. Suggests simple improvements when prompted. Participates in process improvement initiatives. May struggle to see the big picture or systemic issues. Focuses on fixing immediate problems rather than root causes.' FROM capabilities WHERE name = 'Process Improvement' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Identifies process inefficiencies and proposes solutions. Implements minor process improvements independently. Maps out current processes to identify pain points. Uses basic process improvement methods (5 Whys, flowcharting). Engages stakeholders in improvement efforts. Measures impact of improvements.' FROM capabilities WHERE name = 'Process Improvement' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Leads significant process improvement initiatives. Uses advanced methodologies (Lean, Six Sigma, design thinking). Balances multiple objectives (efficiency, quality, cost, experience). Drives adoption of new processes through change management. Measures and reports on process performance metrics. Creates sustainable improvements that stick.' FROM capabilities WHERE name = 'Process Improvement' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Drives organization-wide transformation through process improvement. Builds process improvement capability in others. Influences how the organization thinks about process and efficiency. Sought out by executives for operational transformation. Known for transforming how work gets done. Known for delivering breakthrough improvements in cost, quality, and speed. Sets the standard for operational excellence.' FROM capabilities WHERE name = 'Process Improvement' ON CONFLICT DO NOTHING;

-- Problem Solving levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Tackles straightforward problems with guidance. May jump to solutions before fully understanding the problem. Asks for help when stuck. May struggle with complex or ambiguous problems. Learning problem-solving frameworks and methods. Focuses on finding "an answer" rather than "the best answer".' FROM capabilities WHERE name = 'Problem Solving' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Solves routine and moderately complex problems independently. Defines problems clearly before seeking solutions. Gathers relevant information and considers options. Distinguishes between symptoms and root causes. Knows when to ask for input vs. solve independently. Tests solutions before full implementation.' FROM capabilities WHERE name = 'Problem Solving' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Solves complex problems independently using structured approaches. Develops multiple solution options and evaluates trade-offs. Balances analytical thinking with intuition and experience. Addresses root causes rather than symptoms. Implements solutions that solve the current problem and prevent future ones.' FROM capabilities WHERE name = 'Problem Solving' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Master problem solver who tackles the most complex challenges. Coaches others on problem-solving approaches. Known for solving problems others can''t crack. Brings fresh perspective to long-standing issues. Sought out by senior leaders for the toughest problems. Known for innovative solutions that create competitive advantage. Sets the standard for critical thinking and problem-solving.' FROM capabilities WHERE name = 'Problem Solving' ON CONFLICT DO NOTHING;