-- Delegation levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Completes own work independently but may not yet delegate to others. Understands the concept of delegation but unsure how to implement effectively. May be reluctant to give work to others (wants to do it themselves). When delegating, may provide unclear instructions or insufficient context. Checks in frequently or micromanages due to lack of confidence. Learning to trust others with tasks they previously owned. Focuses more on task completion than developing others through delegation.' FROM capabilities WHERE name = 'Delegation' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Delegates routine tasks and projects appropriately. Provides clear instructions, context, and expectations when delegating. Matches tasks to individuals based on skills and capacity. Monitors progress without micromanaging. Balances delegation with maintaining personal workload. Recognizes delegation as a development opportunity for others. Adjusts level of oversight based on the person and task complexity. Follows up consistently and provides feedback on delegated work.' FROM capabilities WHERE name = 'Delegation' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Masters the art of delegation to maximize team performance and development. Delegates complex projects and significant responsibilities with confidence. Strategically delegates to develop team members'' capabilities. Clearly defines outcomes while empowering others to determine approach. Trusts team members to execute without constant oversight. Provides support and removes obstacles without taking tasks back. Holds people accountable for results while coaching them through challenges. Creates a culture where delegation is seen as empowerment, not dumping.' FROM capabilities WHERE name = 'Delegation' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Balances team empowerment and organizational needs effectively by systematically delegating and developing talent. Influences organizational culture around empowerment. Sought out by other leaders for advice on building high-trust, high-delegation teams. Sets the standard for how effective delegation drives results and growth.' FROM capabilities WHERE name = 'Delegation' ON CONFLICT DO NOTHING;

-- Performance Management levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Provides basic feedback when prompted or during formal review cycles. Focuses primarily on what went wrong rather than balanced feedback. May be uncomfortable giving critical feedback or addressing performance issues. Understands the importance of performance discussions but lacks confidence. Documents performance inconsistently or only when required. Relies heavily on manager guidance for performance conversations. May avoid difficult conversations, hoping issues resolve themselves.' FROM capabilities WHERE name = 'Performance Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Provides regular, timely feedback (both positive and constructive). Conducts performance conversations with increasing confidence. Documents performance consistently and thoroughly. Addresses minor performance issues promptly with direct communication. Sets clear expectations and measurable goals with team members. Balances recognition of achievements with areas for improvement.' FROM capabilities WHERE name = 'Performance Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Manages performance proactively across all team members. Has difficult performance conversations skillfully and compassionately. Creates performance improvement plans and follows through effectively. Differentiates performance across team (identifies top, solid, and struggling performers). Connects individual performance to team and organizational goals. Makes tough decisions when necessary (demotions, terminations).' FROM capabilities WHERE name = 'Performance Management' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Develops other managers'' performance management skills through coaching and training. Designs performance management systems, processes, and frameworks. Handles the most complex performance situations (senior leaders, sensitive issues). Balances high standards with fairness, development, and organizational values. Creates a culture where feedback is continuous, transparent, and developmental. Influences organizational policies and practices around performance and accountability. Builds a culture where expectations are clear and growth is prioritized. Sought out by HR and senior leaders for guidance on performance challenges. Sets the benchmark for how performance management drives results and retention.' FROM capabilities WHERE name = 'Performance Management' ON CONFLICT DO NOTHING;