-- Written Communication levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Writes clearly for basic, routine communication (emails, simple documents). May require multiple drafts or revisions to achieve clarity. Focuses on getting information down but may lack structure or polish. Grammar and punctuation are generally correct but may have occasional errors. Asks for feedback and examples to improve writing. Struggles with complex or formal documents. May not adapt tone/style appropriately for different audiences.' FROM capabilities WHERE name = 'Written Communication' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Writes professional documents across common formats (emails, reports, memos). Organizes information logically with appropriate structure. Adapts tone and style for different audiences (colleagues, clients, leadership). Produces clean drafts with minimal editing required. Uses proper grammar, punctuation, and formatting consistently.' FROM capabilities WHERE name = 'Written Communication' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Writes compelling professional content across all business formats. Crafts clear, persuasive arguments and recommendations. Adapts complex information for diverse audiences (technical to non-technical, junior to executive). Produces polished, publication-ready documents with minimal revision. Writes with appropriate tone for sensitive or difficult situations. Creates documents that drive action and decision-making.' FROM capabilities WHERE name = 'Written Communication' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Coaches others to become better writers. Creates writing standards and templates used organization-wide. Serves as an editor and writing resource for colleagues. Represents the organization in high-stakes external communications. Known for clear, impactful written communication. Known as "the writer" - sought out for the most important documents. Sets the benchmark for written communication excellence.' FROM capabilities WHERE name = 'Written Communication' ON CONFLICT DO NOTHING;

-- Verbal Communication levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Communicates basic information clearly in one-on-one or small group settings. May be nervous or lack confidence in formal settings. Speaks clearly but may ramble or lack structure. Asks clarifying questions when unsure. Listens actively but may miss nuances. Participates in meetings but may not speak up proactively. Struggles with complex explanations or thinking on feet.' FROM capabilities WHERE name = 'Verbal Communication' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Communicates clearly and confidently in most situations. Speaks in an organized, structured manner (clear beginning, middle, end). Adapts communication style to audience and situation. Handles routine conversations and meetings independently. Asks thoughtful questions and actively listens. Speaks up appropriately in meetings and group discussions. Can explain moderately complex topics to others. Growing comfort with impromptu speaking.' FROM capabilities WHERE name = 'Verbal Communication' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Commands attention and engages audiences effectively. Excels at both planned and impromptu speaking. Adapts messaging on the fly based on audience reactions. Facilitates productive discussions and navigates different viewpoints. Handles challenging questions and pushback skillfully. Builds rapport quickly across diverse audiences. Known as an effective, confident communicator.' FROM capabilities WHERE name = 'Verbal Communication' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Exceptional speaker and masterful communicator. Sought out for the most critical conversations and negotiations. Sets the standard for verbal communication excellence. Creates lasting impressions through the spoken word. Influences and persuades at the highest levels.' FROM capabilities WHERE name = 'Verbal Communication' ON CONFLICT DO NOTHING;

-- Presentation Skills levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Delivers simple presentations with preparation and practice. Relies heavily on slides or notes; may read directly from them. Shows nervousness or discomfort presenting to groups. Content may be unclear or poorly organized. Struggles with audience engagement or managing questions. Improves with feedback and practice. Prefers to avoid presenting when possible.' FROM capabilities WHERE name = 'Presentation Skills' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Delivers clear, organized presentations confidently. Uses slides as support rather than crutch. Handles most questions competently. Manages time well and stays on topic. Comfortable presenting to small and medium-sized groups. Creates visually clean, professional slides.' FROM capabilities WHERE name = 'Presentation Skills' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Delivers compelling presentations that inform, persuade, and inspire. Engages audience with eye contact and conversational tone. Commands the room with confidence and executive presence. Adapts presentation style to different audiences. Handles difficult questions and challenges skillfully. Comfortable presenting to executives and large audiences. Known for engaging, impactful presentations.' FROM capabilities WHERE name = 'Presentation Skills' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Exceptional presenter who captivates and influences audiences. Delivers keynote-quality presentations consistently. Creates memorable experiences that drive action and change. Masterfully balances data, story, and emotion. Handles any audience size or setting with ease (boardroom to conference stage). Represents organization at highest-profile events. Sought out for the most critical presentations. Coaches others on presentation skills. Sets the organizational standards for presentations and benchmark for presentation excellence.' FROM capabilities WHERE name = 'Presentation Skills' ON CONFLICT DO NOTHING;

-- Active Listening levels
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Listens to basic information and instructions. May interrupt or finish others'' sentences. Sometimes misses key points or nuances. Shows they''re listening through basic cues (nodding, eye contact). Asks clarifying questions when confused. May be thinking about their response while others are talking. Understands the importance of listening but still developing the skill.' FROM capabilities WHERE name = 'Active Listening' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Listens attentively without interrupting. Hears both content and tone of what''s being said. Asks clarifying and probing questions to deepen understanding. Paraphrases to confirm understanding. Picks up on non-verbal cues and emotions. Gives full attention during conversations (not distracted by phone, computer). Demonstrates empathy and understanding. Responds thoughtfully rather than reactively.' FROM capabilities WHERE name = 'Active Listening' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Creates psychological safety for others to share openly. Asks powerful questions that help others think more deeply. Remembers important details from previous conversations. Balances listening with appropriate input. Adapts listening approach based on the person and situation. Known as someone people trust with sensitive information. Helps others feel truly heard and understood.' FROM capabilities WHERE name = 'Active Listening' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Coaches leaders to become better listeners. Mediates complex conflicts through exceptional listening skills. Sought out for sensitive conversations requiring deep understanding. Influences how the organization values listening. Practices listening as a core leadership capability. Sets the standard for listening as a leadership capability.' FROM capabilities WHERE name = 'Active Listening' ON CONFLICT DO NOTHING;

-- Conflict Resolution levels  
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'foundational', 'Acknowledges conflicts when they exist but unsure how to address them. May avoid confrontation or hope conflicts resolve themselves. Participates in conflict resolution when guided by others. Understands that conflict is normal but lacks confidence in addressing it. May take sides rather than remaining neutral.' FROM capabilities WHERE name = 'Conflict Resolution' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'advancing', 'Addresses conflicts directly and promptly. Facilitates resolution of routine interpersonal conflicts on team. Remains calm and professional during disagreements. Helps parties understand each other''s perspectives. Focuses on interests rather than positions. Finds workable compromises for most situations. Knows when to escalate more serious conflicts.' FROM capabilities WHERE name = 'Conflict Resolution' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'independent', 'Resolves complex conflicts effectively and constructively. Balances advocacy with inquiry during conflicts. Turns conflicts into opportunities for understanding and improvement. Handles emotionally charged situations with composure. Builds stronger relationships through effective conflict resolution. Coaches others on navigating difficult conversations.' FROM capabilities WHERE name = 'Conflict Resolution' ON CONFLICT DO NOTHING;
INSERT INTO capability_levels (capability_id, level, description) SELECT id, 'mastery', 'Master at resolving the most complex and sensitive conflicts. Coaches senior leaders through difficult interpersonal situations. Builds cultures where healthy debate and disagreement are normalized. Sought out by executives for the most challenging people situations. Influences organizational approach to conflict and difficult conversations. Known for building bridges and healing fractured relationships. Sets the standard for turning conflict into collaboration.' FROM capabilities WHERE name = 'Conflict Resolution' ON CONFLICT DO NOTHING;